### ISSUE TITLE
Better detection

### ISSUE THREAD

**Issue by kof** [tuxsudo/is-in-browser#1]
I have got this issue https://github.com/cssinjs/jss/issues/292
It turns out `typeof document` is not good enough, so I was looking for something minimal with more secure detection.

For that particular problem `typeof window`  would work, however I think we can do even better:

``` javascript
   export default typeof window === 'object' && window.document && document.nodeType === 9
```

**Comment by nfriedly** [comment]
You probably also want a `typeof document == 'object'` in there, or else it could choke if there's a global `window` but not a global `document`.
