### ISSUE TITLE
Republish for LICENSE text?

### ISSUE THREAD

**Issue by jeffvandyke** [tuxsudo/is-in-browser#10]
Doing a license audit, and noticed that though the license was added 6 months ago (in 2019), the last publish to NPM (<https://www.npmjs.com/package/is-in-browser>) was 3 years ago (2016). Could you kindly republish this package so that the license is included in the package files?

**Comment by aidinabedi** [comment]
Hello @tuxsudo, any updates on this? Including the license file in the npm package would be extremely valuable and helpful to us as well. Cheers!

**Comment by tuxsudo** [comment]
Published with license in v 2.0.0. Thanks
