### ISSUE TITLE
1.1 breaks commonjs require

### ISSUE THREAD

**Issue by mikeocool** [tuxsudo/is-in-browser#4]
Looks like the latest version broke the ability to require is-in-browser.

Running `npm install is-in-browser`, followed by this script with node cli: `var isBrowser = require('is-in-browser').default;` results in this error: 
```
module.js:327
    throw err;
    ^

Error: Cannot find module 'is-in-browser'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/Users/mike/Projects/node/index.js:1:79)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by codeocelot** [comment]
To add to @mikeocool's comment, it seems that you've left out the `dist` dir out of the published module.  

Edit: `npm install is-in-browser@1.0.2` until this is sorted out.

**Comment by edrpls** [comment]
@codeocelot  It's not there because the prepublish script that generates it was removed from package.json as @reduxdj found out

https://github.com/tuxsudo/is-in-browser/commit/eca5d2806ef1a2af8b82494384f717b9533c733f

**Comment by edrpls** [comment]
In my case is-in-browser is a subdependency so npm install didn't work, I created this npm-shrinkwrap.json file to force the install of 1.0.2:

```
{
  "dependencies": {
    "css-vendor": {
      "version": "0.3.8",
      "from": "css-vendor@0.3.8",
      "dependencies": {
        "is-in-browser": {
          "version": "1.0.2",
          "from": "is-in-browser@1.0.2"
        }
      }
    }
  }
}

```

is-in-browser is a dependency of one of my sub dependencies (react-modal-dialog > jss-vendor-prefixer > css-vendor > is-in-browser), by adding this file to the root of the project npm forced the specific version I wanted to install.

[More info here.](http://stackoverflow.com/a/17423915/1335287)

**Comment by tuxsudo** [comment]
sorry about that 😞
