### ISSUE TITLE
Add licence file

### ISSUE THREAD

**Issue by lexanth** [tuxsudo/is-in-browser#8]
Hi, can you please add a licence file to the project? Also, am I correct assuming the project is under MIT licence just the file is missing? (package.json indicates MIT, that's why I think so)

**Comment by piscis** [comment]
+1  it would be really helpful to have a license text in the repository because this project is a sub dependency of one of the open source libs we are using. We want to add this to our OSA credits section but right now it's kinda hard to know how the correct license looks like

**Comment by tuxsudo** [comment]
Done in #9
